// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOklH2KLFXo5xJC6LzuXxakPbfE1bj4tM',
    appId: '1:598076585741:web:725d39de5bd8fdb9d16244',
    messagingSenderId: '598076585741',
    projectId: 'omusiber-65c94',
    authDomain: 'omusiber-65c94.firebaseapp.com',
    databaseURL: 'https://omusiber-65c94-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'omusiber-65c94.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7PHagxT7t8DpI2gzW5n77QBOfeOgP8Ds',
    appId: '1:598076585741:android:5058c8267faa586bd16244',
    messagingSenderId: '598076585741',
    projectId: 'omusiber-65c94',
    databaseURL: 'https://omusiber-65c94-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'omusiber-65c94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJH_6SKMpvHPmknqQ5IVBkTacBjl87W-o',
    appId: '1:598076585741:ios:236f4cded306be9ed16244',
    messagingSenderId: '598076585741',
    projectId: 'omusiber-65c94',
    databaseURL: 'https://omusiber-65c94-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'omusiber-65c94.firebasestorage.app',
    iosClientId: '598076585741-5404ekkfqie5tg7a0bdrjd3kvpudg1h9.apps.googleusercontent.com',
    iosBundleId: 'me.orbitium.akademiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJH_6SKMpvHPmknqQ5IVBkTacBjl87W-o',
    appId: '1:598076585741:ios:738b9459b7b65c17d16244',
    messagingSenderId: '598076585741',
    projectId: 'omusiber-65c94',
    databaseURL: 'https://omusiber-65c94-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'omusiber-65c94.firebasestorage.app',
    iosClientId: '598076585741-7q7lnic3hlqvm9soroat7tqat5qjqp81.apps.googleusercontent.com',
    iosBundleId: 'com.example.omusiber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOklH2KLFXo5xJC6LzuXxakPbfE1bj4tM',
    appId: '1:598076585741:web:6ed6ff68d8501b58d16244',
    messagingSenderId: '598076585741',
    projectId: 'omusiber-65c94',
    authDomain: 'omusiber-65c94.firebaseapp.com',
    databaseURL: 'https://omusiber-65c94-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'omusiber-65c94.firebasestorage.app',
  );
}
